name: Update Controls

on: 
  workflow_dispatch:

permissions:
  actions: write
  contents: write


jobs:
  get-boundary-controls:
    name: Get Boundary Controls
    runs-on: ubuntu-22.04

    steps:
      - uses: auditmation/auditmation-policy-builder@main
        with:
          operation: load-controls
          api-key: ${{secrets.API_KEY}}
          org-id: ${{secrets.ORG_ID}}
          boundary-id: ${{secrets.BOUNDARY_ID}}
          url: ${{secrets.URL}}
