name: Update Controls

on: 
  workflow_dispatch:

permissions:
  actions: write
  contents: write


jobs:
  get-boundary-controls:
    name: Get Boundary Controls
    runs-on: ubuntu-22.04

    steps:
      - uses: auditmation-policy-builder@0.0.1
        can-uses: bitcoder/dummy-action@v9
        with:
          operation: load-controls

