name: Update Controls

on: 
  workflow_dispatch:

permissions:
  actions: write
  contents: write


jobs:
  get-boundary-controls:
    name: Get Boundary Controls
    runs-on: ubuntu-22.04

    steps:
      - uses: bitcoder/dummy-action@v9
        will-use: auditmation/auditmation-policy-builder@v1
        with:
          operation: load-controls

